const ITEMS_NOT_FOUND = 'ITEMS_NOT_FOUND';
const ITEM_NOT_FOUND = 'ITEM_NOT_FOUND';
const ADD_USER_ERROR = 'ADD_USER_ERROR';

export default {
  ITEMS_NOT_FOUND,
  ITEM_NOT_FOUND,
  ADD_USER_ERROR,
};
